### ISSUE TITLE
Restore config device -Feedback for enhancement 

### ISSUE THREAD

**Issue by parth995** [sachin0987/Cisco-Device-Backup-Ansible#1]
Hi Sachin, It's cool stuff to backup device config using backup modules. 

Have you got thoughts on restoring network configs in interactive way. I mean passing particular file from output folders

**Comment by vsachin094** [comment]
Do you mean , pushing config from local to the device?

**Comment by parth995** [comment]
yep......so I am planning to implement cisco devices backup and restore pipeline. If you can share better ideas would be great. If possible can we connect over linkedin and have a chat ?
My profile - https://www.linkedin.com/in/parth-patel-b8854910a/

**Comment by vsachin094** [comment]
Got it, I will try to add that feature also in this project soon. If you are interested then you can also contribute to this project.

**Comment by parth995** [comment]
Connected over linked. Thanks Sachin. Closing this issue
